from .day1 import DayOneSolution
from .day2 import DayTwoSolution
from .day3 import DayThreeSolution
from .day4 import DayFourSolution
from .day5 import DayFiveSolution
from .day6 import DaySixSolution
from .day7 import DaySevenSolution
from .day8 import DayEightSolution
from .day9 import DayNineSolution
from .day10 import DayTenSolution
from .day11 import DayElevenSolution